### ISSUE TITLE
Cut off text content of <style>

### ISSUE THREAD

**Issue by cortopy** [TobiasNickel/tXml#12]
With the following HTML:

```HTML
<style>p { color: "red" }</style>
```

txml returns:

```
[
      {
        tagName: 'style',
        attributes: {},
        children: [ 'p { color: "red" ' ] // note here the closing bracket is missing
      }
]
```

and so the text content of the <style> tag loses the `}` closing bracket

**Comment by TobiasNickel** [comment]
thanks for pointing that out, It is fixed now. I will publish this at the weekend. until then, you can do a little edit in your node-modules and remove the `-1` from line 162.
