### ISSUE TITLE
Unreachable code as a result of do...while

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [TobiasNickel/tXml#3]
I have noticed that there is unreachable code below this `while` at line 406.
https://github.com/TobiasNickel/tXml/blob/7d678443e6c59b5c8516d4e806abb611a87c2619/tXml.js#L406
Why is the `while` condition `1`, or always true?

**Comment by TobiasNickel** [comment]
Thanks, that is a good point. what a luck it is not harm the functionality.

I guess, I wanted to avoid having the condition in two places, but the result of the condition could actually also be stored in a variable. When I made it, I tried everything to get out performance. Avoiding a variable or a duplicated check come in handy. 

I think today I would introduce a variable, as transpilers and javascript engines optimize that perfectly.
