### ISSUE TITLE
simplify is not invoked like described by the README.md

### ISSUE THREAD

**Issue by derMart** [TobiasNickel/tXml#8]
Hi,

README.md states:
`tXml("<user is='great'><name>Tobias</name><familyName>Nickel</familyName><profession>Software Developer</profession><location>Shanghai / China</location></user>",{simplify:1});`

however, simplify is not invoked like this. Rather it is invoked by:
`tXml.simplify(tXml(xmlString));`

kind regards
Martin

**Comment by TobiasNickel** [comment]
Thanks Martin, for pointing that out.
I think it was an old leftover, before I had this option. 
It is fixed and published, to npm now.
Do you think a `parseSimplified` method would be nice?
